### ISSUE TITLE
Lab 14 missing from repo

### ISSUE THREAD

**Issue by MOC-Labs-Review** [MicrosoftLearning/AZ500-AzureSecurityTechnologies.de-de#1]
![image](https://user-images.githubusercontent.com/91673275/191358076-017caa99-a43d-4fd3-bf38-085c2d45d34a.png)
Lab 14 missing from repo

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
![image](https://user-images.githubusercontent.com/49666210/215968361-d5eaf745-8efc-4c18-82f7-6647b799ca51.png)
fixed. should be close it.
https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies.de-de/blob/OLPRODLOC/Instructions/Labs/LAB_14_Microsoft%20Defender%20for%20Cloud.md

**Comment by chriscarty00** [comment]
Closing - fixed
